[[steps]]
name = "Run tests"
command = [
  "fluentci run --wasm cmake generate",
  "fluentci run --wasm cmake make",
  "fluentci run --wasm cmake make test",
]

[[steps]]
name = "Build"
command = [
  "fluentci run --wasm cmake generate",
  "fluentci run --wasm cmake make",
]
